# استخدم صورة الـ SDK للبناء
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# نسخ كل الملفات
COPY . .

# استعادة الحزم
RUN dotnet restore RealEstateAPI/RealEstateAPI.csproj

# بناء التطبيق
RUN dotnet publish RealEstateAPI/RealEstateAPI.csproj -c Release -o /build --no-restore

# إنشاء مرحلة التشغيل
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /build/ .

# تشغيل التطبيق
ENTRYPOINT ["dotnet", "RealEstateAPI.dll"]
