# المرحلة الأولى: البناء باستخدام Node.js
FROM node:20-slim AS builder

# ضبط الحد الأقصى للذاكرة لـ Node.js
ENV NODE_OPTIONS=--max-old-space-size=1024

# تثبيت الأدوات اللازمة للبناء
RUN apt-get update && apt-get install -y python3 make g++ && rm -rf /var/lib/apt/lists/*

# تعيين الدليل للعمل داخل الحاوية
WORKDIR /app

# نسخ الملفات اللازمة للتثبيت
COPY package*.json ./

# تثبيت التبعيات
RUN npm install --legacy-peer-deps

# نسخ باقي الملفات وبناء المشروع
COPY . .

# تشغيل البناء
RUN npm run build

# المرحلة الثانية: استخدام NGINX لعرض التطبيق
FROM nginx:alpine

# إزالة ملفات الـ NGINX الافتراضية
RUN rm -rf /usr/share/nginx/html/*

# نسخ الملفات المبنية من المرحلة الأولى
COPY --from=builder /app/dist /usr/share/nginx/html

# فتح المنفذ 80
EXPOSE 80

# تشغيل NGINX
CMD ["nginx", "-g", "daemon off;"]
