# مرحلة البناء (Builder)
FROM node:20-alpine@sha256:8bda036ddd59ea51a23bc1a1035d3b5c614e72c01366d989f4120e8adca196d4 AS builder

WORKDIR /app

# نسخ ملفات الـ package فقط لتقليل الكاش والبناء
COPY package*.json ./

# تثبيت بدون dev dependencies لتقليل الذاكرة
RUN npm install --omit=dev && npm cache clean --force

# نسخ بقية ملفات المشروع
COPY . .

# بناء المشروع
RUN npm run build

# المرحلة النهائية (Production)
FROM nginx:alpine@sha256:4ff102c5d78d254a6f0da062b3cf39eaf07f01eec0927fd21e219d0af8bc0591

WORKDIR /usr/share/nginx/html

# حذف المحتوى القديم
RUN rm -rf ./*

# نسخ الملفات المبنية من مرحلة البناء
COPY --from=builder /app/dist .

# نسخ إعدادات NGINX
COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
