version: "3.7"

services:

  # DataBase Service
  database:
    image: ahmedmostafa22/sql-server:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 10s 
        max_attempts: 3     
    env_file:
      - ./Database/.env
    volumes:
      - database-data:/var/opt/mssql/
    networks:
      - internal-network
   
  # BackEnd Service
  backend:
    image: ahmedmostafa22/dotnet-app:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 10s 
        max_attempts: 3
    networks:
      - internal-network
    
  # FrontEnd Service
  frontend:
    image: ahmedmostafa22/frontend:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 10s 
        max_attempts: 3
    networks:
      - internal-network
    ports:
      - target: 80  
        published: 80

# Volume for Data of DataBase
volumes: 
  database-data:

# Networks
networks:
  internal-network:
    driver: overlay
