version: "3.8"

services:
  database:
    image: ahmedmostafa22/sql-server:latest
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
      restart_policy:
        condition: on-failure
    env_file:
      - ./Database/.env
    volumes:
      - database-data:/var/opt/mssql/
    networks:
      - internal-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1433"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

  backend:
    image: ahmedmostafa22/propease-backend:latest  
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
      restart_policy:
        condition: on-failure
    networks:
      - internal-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

  frontend:
    image: ahmedmostafa22/propease-frontend:latest  
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
      restart_policy:
        condition: on-failure
    networks:
      - internal-network
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

volumes: 
  database-data:

networks:
  internal-network:
    driver: overlay
