FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# نسخ ملفات المشروع
COPY RealEstateAPI.csproj .
#COPY RealEstateAPI.sln .

# استعادة التبعيات
RUN dotnet restore

# نسخ بقية ملفات التطبيق
COPY . .

# تثبيت dotnet-ef
RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

# تغيير الدليل إلى مجلد المشروع
#WORKDIR /src/RealEstateAPI

# بناء المشروع
ARG BUILD_CONFIGURATION=Release
RUN dotnet build -c ${BUILD_CONFIGURATION} --output /app/build

#RUN dotnet ef migrations add AutoMigration --output-dir Migrations
# تحديث قاعدة البيانات
#RUN dotnet ef database update

#WORKDIR /src

# بناء التطبيق
RUN dotnet publish RealEstateAPI.csproj -c Release -o /build --no-restore

# إنشاء مرحلة التشغيل
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /build/ .

# تشغيل التطبيق
ENTRYPOINT ["dotnet", "RealEstateAPI.dll"]